# Generated by Django 4.2.7 on 2026-01-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=10)),
                ('election_id', models.CharField(max_length=50)),
                ('otp_stage', models.CharField(choices=[('vote_email', 'First OTP (vote confirmation)'), ('email', 'Second OTP (email confirmation)')], max_length=20)),
                ('otp_value', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
