# Generated by Django 4.2.7 on 2025-11-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='father_name',
        ),
    ]
