# Generated by Django 4.2.7 on 2025-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0002_remove_candidates_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voters',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
