# Generated by Django 4.2.7 on 2025-12-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0003_candidates_father_name_voters_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
