# Generated by Django 4.2.7 on 2025-12-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0004_voters_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='constituency',
        ),
    ]
