# Generated by Django 4.2.7 on 2026-01-09 16:40

import EC_Admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EC_Admin', '0005_remove_candidates_constituency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='dateofbirth',
            field=models.DateField(validators=[EC_Admin.models.validate_voter_age]),
        ),
    ]
